version: '3.3'

services:

  rookie-app:
    container_name: rookie-app
    image: rookie-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./logs:/root/logs
